### ISSUE TITLE
Extension breaks Expand Diff buttons

### ISSUE THREAD

**Issue by aripollak** [petebacondarwin/github-pr-helper#17]
Hi,

When I have this extension loaded, the Expand buttons on the Files Changed tab of PRs (located on the left of diff hunk boundaries) don't do anything. It would be great to be able to use that feature along with this extension.

Thanks for this useful addon!
Ari

**Comment by petebacondarwin** [comment]
Hi @aripollak,
Thanks for raising this issue.  I'll look into it tomorrow.

**Comment by cce** [comment]
I've noticed this too — clicking on links to #targets like comments and the "files changed" tab of PRs adds a trailing slash after the #, so that a link like

https://github.com/acct/repo/pull/4022/files#diff-0

becomes

https://github.com/acct/repo/pull/4022/files#/diff-0

when this plugin is enabled.

**Comment by aripollak** [comment]
Looks like this extension is no longer needed since GitHub finally improved their PR pages?

**Comment by petebacondarwin** [comment]
This does seem to be the case. Glad I don't have to fix this issue then!

Can anyone tell if the new github api is still missing anything useful that
this extension does?

**Comment by cce** [comment]
Your extension shows the labels & their colors on the pulls list, which is
nice and Github still hasn't done that ...

Thanks for your efforts btw!

On Wed, Jan 29, 2014 at 2:17 PM, Pete Bacon Darwin <notifications@github.com

> wrote:
> 
> This does seem to be the case. Glad I don't have to fix this issue then!
> 
> Can anyone tell if the new github api is still missing anything useful that
> this extension does?
>
